title: PiBox Page
description: This page provides an overview of the project including relevant links to usefull Rasperry Pi Resources
show_downloads: true
comments: true
logo_url: https://cdn.pixabay.com/photo/2014/12/18/13/53/raspberry-pi-572481_1280.jpg
google_analytics:
git_branch: gh-pages
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
